# id приложения  желательно указывать всегда в микросервисных приложениях
spring:
  application:
    name: notification-server

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        order_delivered_channel: order_delivered

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectionTimeout: 5000
          timeout: 5000
          writeTimeout: 5000

messages:
  basename: messages

# url, куда будет происходить регистрация микросервисов и другие важные действия
eureka:
  client:
    service-url.defaultZone: http://localhost:8081/eureka

server:
  port: 0

logging:
  level:
    root: info